# Code generated by sial-686

.text
.align 16
# B=?    A=?
# MODSTART

# Entry to: start
# ENTRY   K5 C115 C116 C97 C114 C116
# LAB     L1
LA1:
 movl %ebp,(%edx)
 movl %edx,%ebp
 popl %edx
 movl %edx,4(%ebp)
 movl %eax,8(%ebp)
 movl %ebx,12(%ebp)
# B=?    A=AP3
# B=?    A=AP3
# L       K0
 xorl %ebx,%ebx
# B=?    A=A
# B=?    A=A
# RTN
# moveA2A
 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# B=?    A=?
# moveB2B
# B=B    A=?
# moveA2A
# B=B    A=A
# GLOBAL K1
.globl prog
.globl _prog
prog:
_prog:
 movl 444(%edi),%eax
# G1 L1
 movl $LA1,4(%eax)
# G1
 ret
# B=?    A=?
# MODEND
