

t:	
	(cd com32; cintsys -c c bc32all)
	cintsys -c c rbc32 bcpl
	cintsys -c c rbc32 bcplarg
	cintsys -c c rbc32 bcplsyn
	cintsys -c c rbc32 bcpltrn
	cintsys -c c rbc32 bcplccg
	cintsys -c c rdf bcpl
	cintsys -c c rdf bcplarg
	cintsys -c c rdf bcplsyn
	cintsys -c c rdf bcpltrn
	cintsys -c c rdf bcplccg
	cintsys -c c df BCPL
	cintsys -c c df BCPLARG
	cintsys -c c df BCPLSYN
	cintsys -c c df BCPLTRN
	cintsys -c c df BCPLCCG
	diff map/BCPL.map rmap/bcpl.map >bcpl.diffs
	diff map/BCPLARG.map rmap/bcplarg.map >arg.diffs
	diff map/BCPLSYN.map rmap/bcplsyn.map >syn.diffs
	diff map/BCPLTRN.map rmap/bcpltrn.map >trn.diffs
	diff map/BCPLCCG.map rmap/bcplccg.map >ccg.diffs







