SECTION "sial-rv64im"

GET "libhdr"

GET "sial.h"

/*
 * The register usage is as follows:
 *
 * ra   m/c return address (previous PC)
 * a0   A
 * a1   B
 * a2   C
 * a3   m/c addr P
 * a4   m/c addr G
 */


GLOBAL $(
sialin:   200
asmout:   201
stdin:    202
stdout:   203

rdf:      210
rdp:      211
rdg:      212
rdk:      213
rdw:      215
rdl:      216
rdc:      218
rdcode:   219

pval:     220
gval:     221
kval:     222
wval:     224
lval:     225
mval:     226

scan:     230
cvf:      231
cvfp:     232
cvfg:     233
cvfk:     234
cvfw:     236
cvfl:     237

sectname: 250
modletter:251
charv:    252
labnumber:253
$)

LET start() = VALOF
$( LET argv = VEC 20
   LET v    = VEC 20
   LET cv   = VEC 256/bytesperword

   sectname := v
   sectname%0 := 0
   modletter := 'A'
   charv := cv
   labnumber := 0

   asmout := 0
   stdout := output()
   IF rdargs("FROM,TO/K", argv, 20)=0 DO
   $( writes("Bad args for sial-rv64im*n")
      RESULTIS 20
   $)
   IF argv!0=0 DO argv!0 := "prog.sial"
   IF argv!1=0 DO argv!1 := "prog.s"
   sialin := findinput(argv!0)
   IF sialin=0 DO
   $( writef("Trouble with file %s*n", argv!0)
      RESULTIS 20
   $)
   asmout := findoutput(argv!1)
   
   IF asmout=0 DO
   $( writef("Trouble with file %s*n", argv!1)
      RESULTIS 20
   $)
   
   writef("Converting %s to %s*n", argv!0, argv!1)
   selectinput(sialin)
   selectoutput(asmout)

   writef(";  Code generated by sial-rv64im*n*n")
   writef(" include *"registers.inc*"*n")
   writef("*n align 8*n")

   scan()
   endread()
   UNLESS asmout=stdout DO endwrite()
   selectoutput(stdout)
   writef("Conversion complete*n")
   RESULTIS 0
$)

AND nextlab() = VALOF
{ labnumber := labnumber+1
  RESULTIS labnumber
}

// argument may be of form Ln
AND rdcode(let) = VALOF
$( LET a, ch, neg = 0, ?, FALSE

   ch := rdch() REPEATWHILE ch='*s' | ch='*n'

   IF ch=endstreamch RESULTIS -1

   UNLESS ch=let DO error("Bad item, looking for %c found %c*n", let, ch)

   ch := rdch()

   IF ch='-' DO { neg := TRUE; ch := rdch() }

   WHILE '0'<=ch<='9' DO $( a := 10*a + ch - '0'; ch := rdch()  $)

   RESULTIS neg -> -a, a
$)

AND rdf() = rdcode('F')
AND rdp() = VALOF { pval := rdcode('P'); RESULTIS pval }
AND rdg() = VALOF { gval := rdcode('G'); RESULTIS gval }
AND rdk() = VALOF { kval := rdcode('K'); RESULTIS kval }
AND rdw() = VALOF { wval := rdcode('W'); RESULTIS wval }
AND rdl() = VALOF { lval := rdcode('L'); RESULTIS lval }
AND rdm() = VALOF { mval := rdcode('M'); RESULTIS mval }
AND rdc() = rdcode('C')

AND error(mess, a, b, c) BE
$( LET out = output()
   UNLESS out=stdout DO
   $( selectoutput(stdout)
      writef(mess, a, b, c)
      selectoutput(out)
   $)
   writef(mess, a, b, c)
$)

AND a.call(val) BE
{
   LET ofs = 8*val

   TEST fits.12.bits(ofs) THEN {
      writef("*n sd a3,%n(a3)", ofs)
      writef("*n addi a3,a3,%n", ofs)
      writef("*n addi t0,a0,0")
      writef("*n addi a0,a1,0")
      writef("*n jalr ra,0(t0)")
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n sd a3,%n(t0)", ofs & #xFFF)
      writef("*n addi a3,t0,%n", ofs & #xFFF)
      writef("*n addi t0,a0,0")
      writef("*n addi a0,a1,0")
      writef("*n jalr ra,0(t0)")
   }
   ELSE
      error.64.bits()
}

AND Gg.fetch.reg.set(val, reg) BE
{
   LET ofs = 8*val

   TEST fits.12.bits(ofs) THEN {
      writef("*n ld %s,%n(a4)", reg, ofs)
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui %s,%n", reg, ofs)
      writef("*n add %s,%s,a4", reg, reg)
      writef("*n ld %s,%n(%s)", reg, ofs & #xFFF, reg)
   }
   ELSE
      error.64.bits()
}

AND Gg.call(gval, pval) BE
{
   LET ofs = 8*pval

   Gg.fetch.reg.set(gval, "t0")

   TEST fits.12.bits(ofs) THEN {
      writef("*n sd a3,%n(a3)", ofs)
      writef("*n addi a3,a3,%n", ofs)
      writef("*n jalr ra,0(t0)")
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n sd a3,%n(t0)", ofs & #xFFF)
      writef("*n addi a3,t0,%n", ofs & #xFFF)
      writef("*n jalr ra,0(t0)")
   }
   ELSE
      error.64.bits()
}

AND atb() BE
{
   writef("*n addi a1,a0,0")
}

AND lit.add(val) BE
{
   TEST fits.12.bits(val) THEN
      writef("*n addi a0,a0,%n", val)
   ELSE TEST fits.32.bits(val) THEN {
      IF val & #x800 THEN val := val + 4096

      writef("*n lui t0,%n", val)
      writef("*n add a0,a0,t0")
      writef("*n addi a0,a0,%n", val & #xFFF)
   }
   ELSE
      error.64.bits()
}

AND base.n.add.fetch.lit.add.a.set(base, pval, kval) BE
{
   base.n.add.fetch.a.set(base, pval)
   lit.add(kval)
}

// -- start of RISC-V helpers --

AND error.64.bits() BE
{
   writef("*n.error Need 64-bit operand support")
}

AND fits.12.bits(n) = VALOF {
   RESULTIS (-2048 <= n) & (n < 2048)
}

AND fits.32.bits(n) = VALOF {
   // ASSUMES 32-bit BCPL.  I tried using range-based testing earlier, but
   // the condition kept failing because it kept ignoring bits 63..32.
   RESULTIS n ~= #x8000_0000
}

AND base.n.add.fetch.a.set(base, n) BE
{
   LET ofs = 8*n
   TEST fits.12.bits(ofs) THEN writef("*n ld a0,%n(a%n)", ofs, base)
   ELSE TEST fits.32.bits(ofs) THEN {
      // Account for sign extension of LD instruction offset
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n add t0,t0,a%n", base)
      writef("*n ld a0,%n(t0)", ofs & #xFFF)
   }
   ELSE
      error.64.bits()
}

AND base.n.add.fetch.a.add(base, n) BE
{
   LET ofs = 8*n
   TEST fits.12.bits(ofs) THEN {
      writef("*n ld t0,%n(a%n)", ofs, base)
      writef("*n add a0,a0,t0")
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n ld t0,%n(t0)", ofs & #xFFF)
      writef("*n add a0,a0,t0")
   }
   ELSE
      error.64.bits()
}

AND base.n.add.a.set.shift(n, base) BE
{
   LET ofs = 8*n
   TEST fits.12.bits(ofs) THEN {
      writef("*n addi a0,a%n,%n", base, ofs)
      writef("*n srai a0,a0,3")
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      // Account for sign extension of LD instruction offset
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n addi t0,t0,%n", ofs & #xFFF)
      writef("*n add a0,t0,a%n", base)
      writef("*n srai a0,a0,3")
   }
   ELSE
      error.64.bits()
}

AND label.addr.reg.set(reg, prefix, modletter, labelval) BE
{
   LET xval = nextlab()

   writef("*nX%c%n:", modletter, xval)
   writef("*n auipc %s,%c%c%n-X%c%n+2048", reg, prefix, modletter, labelval, modletter, xval)
   writef("*n addi %s,%s,%c%c%n-X%c%n", reg, reg, prefix, modletter, labelval, modletter, xval)
}

AND label.fetch.reg.set(modletter, labelval, reg) BE
{
   label.addr.reg.set(reg, 'L', modletter, labelval)
   writef("*n ld %s,0(%s)", reg, reg)
}

AND label.fetch.a.set(modletter, labelval) BE label.fetch.reg.set(modletter, labelval, "a0")

AND label.reg.set(reg, prefix, modletter, labelval) BE label.addr.reg.set(reg, prefix, modletter, labelval)

AND label.a.set(prefix, modletter, labelval) BE
{
   label.reg.set("a0", prefix, modletter, labelval)
}

AND label.a.set.shift(prefix, modletter, labelval) BE
{
   label.a.set(prefix, modletter, labelval)
   writef("*n srai a0,a0,3")
}

AND label.a.store(prefix, modletter, labelval) BE
{
   label.reg.set("t0", prefix, modletter, labelval)
   writef("*n sd a0,0(t0)")
}

AND lit.reg.set(kval, reg) BE
{
   TEST fits.12.bits(kval) THEN
      writef("*n addi %s,x0,%n", reg, kval)
   ELSE TEST fits.32.bits(kval) THEN {
      writef("*n lui %s,%n", reg, kval + (kval & #x800 -> 4096, 0))
      writef("*n addi %s,%s,%n", reg, reg, kval & #xFFF)
   }
   ELSE
      error.64.bits()
}

AND lit.a.set(kval) BE lit.reg.set(kval, "a0")

AND base.n.add.reg.store(reg, base, val) BE
{
   LET ofs = 8*val
   TEST fits.12.bits(ofs) THEN
      writef("*n sd %s,%n(a%n)", reg, ofs, base)
   ELSE TEST fits.32.bits(ofs) THEN {
      // Account for sign extension of ST instruction offset
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n add t0,t0,a%n", base)
      writef("*n sd a0,%n(t0)", ofs & #xFFF)
   }
   ELSE
      error.64.bits()
}

AND base.n.add.a.store(base, val) BE base.n.add.reg.store("a0", base, val)

AND lit.a.incr(val) BE
{
   IF val ~= 0 THEN {
      TEST fits.12.bits(val) THEN {
         writef("*n addi a0,a0,%n", val)
      }
      ELSE TEST fits.32.bits(val) THEN {
         IF val & #x800 THEN val := val + 4096
         writef("*n lui t0,%n", val)
         writef("*n addi t0,t0,%n", val & #xFFF)
         writef("*n add a0,a0,t0")
      }
      ELSE
         error.64.bits()
   }
}

AND lit.a.decr(val) BE lit.a.incr(-val)

AND reg.n.add.fetch.a.set(reg, val) BE
{
   LET ofs = 8 * val

   TEST fits.12.bits(ofs) THEN {
      writef("*n ld a0,%n(%s)", ofs, reg)
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n add t0,t0,%s", reg)
      writef("*n ld a0,%n(t0)", ofs & #xFFF)
   }
   ELSE
      error.64.bits()
}

AND reg.a.add.fetch.a.set(reg) BE
{
   writef("*n slli a0,a0,3")
   writef("*n add a0,a0,%s", reg)
   writef("*n ld a0,0(a0)")
}

AND a.n.add.fetch.a.set(val) BE
{
   LET ofs = 8*val

   TEST fits.12.bits(ofs) THEN {
      writef("*n slli a0,a0,3")
      writef("*n ld a0,%n(a0)", ofs)
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n add a0,a0,t0")
      writef("*n slli a0,a0,3")
      writef("*n ld a0,%n(a0)", ofs & #xFFF)
   }
   ELSE
      error.64.bits()
}

AND b.a.store() BE
{
   writef("*n slli a0,a0,3")
   writef("*n sd a1,0(a0)")
}

AND base.n.add.fetch.a.add.b.store(base, val) BE
{
   LET ofs = 8*val

   TEST fits.12.bits(ofs) THEN {
      writef("*n ld t0,%n(a%n)", ofs, base)
      writef("*n add t0,t0,a0")
      writef("*n slli t0,t0,3")
      writef("*n sd a1,0(t0)")
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t0,%n", ofs)
      writef("*n add t0,t0,a%n", base)
      writef("*n ld t0,%n(t0)", ofs & #xFFF)
      writef("*n add t0,t0,a0")
      writef("*n slli t0,t0,3")
      writef("*n sd a1,0(t0)")
   }
   ELSE
      error.64.bits()
}

AND a.n.add.shift.b.store(val) BE
{
   TEST fits.12.bits(val) THEN {
      writef("*n addi t0,a0,%n", val)
      writef("*n slli t0,t0,3")
      writef("*n sd a1,0(t0)")
   }
   ELSE TEST fits.32.bits(val) THEN {
      IF val & #x800 THEN val := val + 4096

      writef("*n lui t0,%n", val)
      writef("*n addi t0,t0,%n", val & #xFFF)
      writef("*n add t0,t0,a0")
      writef("*n slli t0,t0,3")
      writef("*n sd a1,0(t0)")
   }
   ELSE
      error.64.bits()
}

AND base.n.add.fetch.reg.set(base, val, reg) BE
{
   LET ofs = 8*val

   TEST fits.12.bits(ofs) THEN {
      writef("*n ld %s,%n(a%n)", reg, ofs, base)
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui %s,%n", reg, ofs)
      writef("*n add %s,%s,a%n", reg, reg, base)
      writef("*n ld %s,%n(%s)", reg, ofs & #xFFF, reg)
   }
   ELSE
      error.64.bits()
}

AND reg.n.add.a.store(reg, val) BE
{
   LET ofs = 8*val

   TEST fits.12.bits(ofs) THEN {
      writef("*n sd a0,%n(%s)", ofs, reg)
   }
   ELSE TEST fits.32.bits(ofs) THEN {
      IF ofs & #x800 THEN ofs := ofs + 4096

      writef("*n lui t1,%n", ofs)
      writef("*n add %s,%s,t1", reg, reg)
      writef("*n sd a0,%n(%s)", ofs & #xFFF, reg)
   }
   ELSE
      error.64.bits()
}

AND base.n.add.fetch.k.add.a.store(base, v1, v2) BE
{
   base.n.add.fetch.reg.set(base, v1, "t0")
   writef("*n slli t0,t0,3")
   reg.n.add.a.store("t0", v2)
}

// -- end of RISC-V helpers --

AND scan() BE
$( LET op = rdf()

   SWITCHON op INTO

   $( DEFAULT:       error(";  Bad op %n*n", op); LOOP

      CASE -1:       RETURN
     
      CASE f_lp:     cvfp("LP") // a := P!n
                     base.n.add.fetch.a.set(3, pval)
                     ENDCASE

      CASE f_lg:     cvfg("LG") // a := G!n
                     base.n.add.fetch.a.set(4, gval)
                     ENDCASE

      CASE f_ll:     cvfl("LL") // a := !Ln
                     label.fetch.a.set(modletter, lval)
                     ENDCASE

      CASE f_llp:    cvfp("LLP") // a := @ P!n
                     base.n.add.a.set.shift(pval, 3)
                     ENDCASE

      CASE f_llg:    cvfg("LLG") // a := @ G!n
                     base.n.add.a.set.shift(gval, 4)
                     ENDCASE

      CASE f_lll:    cvfl("LLL") // a := @ !Ln
                     label.a.set.shift('L', modletter, lval)
                     ENDCASE

      CASE f_lf:     cvfl("LF") // a := byte address of Ln
                     label.a.set('L', modletter, lval)
                     ENDCASE

      CASE f_lw:     cvfm("LW")
                     label.a.set('M', modletter, mval)
                     ENDCASE

      CASE f_l:      cvfk("L") // a := n
                     lit.a.set(kval)
                     ENDCASE

      CASE f_lm:     cvfk("LM") // a := -n
                     lit.a.set(-kval)
                     ENDCASE

      CASE f_sp:     cvfp("SP") // P!n := a
                     base.n.add.a.store(3, pval)
                     ENDCASE

      CASE f_sg:     cvfg("SG") // G!n := a
                     base.n.add.a.store(4, gval)
                     ENDCASE

      CASE f_sl:     cvfl("SL") // !Ln := a
                     label.a.store('L', modletter, lval)
                     ENDCASE

      CASE f_ap:     cvfp("AP") // a := a + P!n
                     base.n.add.fetch.a.add(3, pval)
                     ENDCASE

      CASE f_ag:     cvfg("AG") // a := a + G!n
                     base.n.add.fetch.a.add(4, gval)
                     ENDCASE

      CASE f_a:      cvfk("A") // a := a + n
                     lit.a.incr(kval)
                     ENDCASE

      CASE f_s:      cvfk("S")  // a := a - n
                     lit.a.decr(kval)
                     ENDCASE

      CASE f_lkp:    cvfkp("LKP") // a := P!n!k
                     base.n.add.fetch.reg.set(3, pval, "t0")
                     writef("*n slli t0,t0,3")
                     reg.n.add.fetch.a.set("t0", kval)
                     ENDCASE

      CASE f_lkg:    cvfkg("LKG") // a := G!n!k
                     base.n.add.fetch.reg.set("t0", 4, gval)
                     writef("*n slli t0,t0,3")
                     reg.n.add.fetch.a.set("t0", kval)
                     ENDCASE

      CASE f_rv:     cvf("RV")  // a := ! a
                     writef("*n slli a0,a0,3")
                     writef("*n ld a0,0(a0)")
                     ENDCASE

      CASE f_rvp:    cvfp("RVP") // a := P!n!a
                     base.n.add.fetch.reg.set("t0", 3, pval)
                     reg.a.add.fetch.a.set("t0")
                     ENDCASE

      CASE f_rvk:    cvfk("RVK") // a := a!k
                     a.n.add.fetch.a.set(kval)
                     ENDCASE

      CASE f_st:     cvf("ST") // !a := b
                     b.a.store()
                     ENDCASE

      CASE f_stp:    cvfp("STP") // P!n!a := b
                     base.n.add.fetch.a.add.b.store(3, pval)
                     ENDCASE

      CASE f_stk:    cvfk("STK") // a!n := b
                     a.n.add.shift.b.store(kval)
                     ENDCASE

      CASE f_stkp:   cvfkp("STKP")  // P!n!k := a
                     base.n.add.fetch.k.add.a.store(3, pval, kval)
                     ENDCASE

      CASE f_skg:    cvfkg("SKG") // G!n!k := a
                     base.n.add.fetch.k.add.a.store(4, gval, kval)
                     ENDCASE

      CASE f_xst:    cvf("XST") // !b := a
      		     writef("*n slli a1,a1,3")
                     writef("*n sd a0,0(a1)")
                     ENDCASE

      CASE f_k:      cvfp("K") // Call  a(b,...) incrementing P by n
                     a.call(pval)
                     ENDCASE

      CASE f_kpg:    cvfpg("KPG") // Call Gg(a,...) incrementing P by n
                     Gg.call(gval, pval)
                     ENDCASE

      CASE f_neg:    cvf("NEG") // a := - a
                     writef("*n sub a0,x0,a0")
                     ENDCASE

      CASE f_not:    cvf("NOT") // a := ~ a
                     writef("*n xori a0,a0,-1")
                     ENDCASE

      CASE f_abs:    cvf("ABS") // a := ABS a
                   { LET l = nextlab()
                     writef("*n bge a0,x0,S%c%n", modletter, l)
                     writef("*n sub a0,x0,a0")
                     writef("*nS%c%n:", modletter, l)
                     ENDCASE
                   }

      CASE f_xdiv:   cvf("XDIV") // a := a / b
                     writef("*n div a0,a0,a1")
                     ENDCASE

      CASE f_xmod:   cvf("XMOD") // a := a mod b
                     writef("*n mod a0,a0,a1")
                     ENDCASE

      CASE f_xsub:   cvf("XSUB") // a := a - b
                     writef("*n sub a0,a1,a0")
                     ENDCASE

      CASE f_mul:    cvf("MUL") // a := b * a; c := ?
                     writef("*n mul a0,a1,a0")
                     ENDCASE

      CASE f_div:    cvf("DIV")  // a := b / a; c := ?
                     writef("*n div a0,a1,a0")
                     ENDCASE

      CASE f_mod:    cvf("MOD") // a := b REM a; c := ?
                     writef("*n mod a0,a1,a0")
                     ENDCASE

      CASE f_add:    cvf("ADD") // a := b + a
                     writef("*n add a0,a1,a0")
                     ENDCASE

      CASE f_sub:    cvf("SUB") // a := b - a
                     writef("*n sub a0,a1,a0")
                     ENDCASE

      CASE f_eq:     cvf("EQ") // a := b = a
                     writef("*n xor a0,a0,a1")
                     writef("*n sltiu a0,a0,1") // 1 if a0 < 1
                     writef("*n sub a0,x0,a0")  // make truth = -1 or 0
                     ENDCASE

      CASE f_ne:     cvf("NE") // a := b ~= a
                     writef("*n xor a0,a0,a1")
                     writef("*n sltu a0,x0,a0") // 1 if 0 < a0
                     writef("*n sub a0,x0,a0")  // make truth = -1 or 0
                     ENDCASE

      CASE f_ls:     cvf("LS") // a := b < a
                     writef("*n slt a0,a1,a0")
                     writef("*n sub a0,x0,a0")
                     ENDCASE

      CASE f_gr:     cvf("GR") // a := b > a
                     writef("*n slt a0,a0,a1")
                     writef("*n sub a0,x0,a0")
                     ENDCASE

      CASE f_le:     cvf("LE") // a := b <= a, aka a := ~(b > a)
                     writef("*n slt a0,a0,a1")
                     writef("*n xori a0,a0,1")
                     writef("*n sub a0,x0,a0")
                     ENDCASE

      CASE f_ge:     cvf("GE") // a := b >= a, aka a := ~(b < a)
                     writef("*n slt a0,a1,a0")
                     writef("*n xori a0,a0,1")
                     writef("*n sub a0,x0,a0")
                     ENDCASE

      CASE f_eq0:    cvf("EQ0") // a := a = 0
                     writef("*n sltiu a0,a0,1") // 1 if a0 < 1
                     writef("*n sub a0,x0,a0")  // make truth = -1 or 0
                     ENDCASE

      CASE f_ne0:    cvf("NE0") // a := a ~= 0
                     writef("*n sltu a0,x0,a0") // 1 if 0 < a0
                     writef("*n sub a0,x0,a0")  // make truth = -1 or 0
                     ENDCASE

      CASE f_ls0:    cvf("LS0") // a := a < 0
                     writef("*n srai a0,a0,63")
                     ENDCASE

      CASE f_gr0:    cvf("GR0") // a := a > 0
                     writef("*n slt a0,x0,a0")
                     writef("*n sub a0,x0,a0")
                     ENDCASE

      CASE f_le0:    cvf("LE0") // a := a <= 0
                     writef("*n slt a0,x0,a0")
                     writef("*n xori a0,a0,1")
                     writef("*n sub a0,x0,a0")
                     ENDCASE

      CASE f_ge0:    cvf("GE0") // a := a >= 0
                     writef("*n srai a0,a0,63")
                     writef("*n xori a0,a0,-1")
                     ENDCASE

      CASE f_lsh:    cvf("LSH") // a := b << a
                     writef("*n sll a0,a1,a0")
                     ENDCASE

      CASE f_rsh:    cvf("RSH") // a := b >> a 
                     writef("*n sra a0,a1,a0")
                     ENDCASE

      CASE f_and:    cvf("AND") // a := b & a 
                     writef("*n and a0,a1,a0") 
                     ENDCASE

      CASE f_or:     cvf("OR") // a := b | a 
                     writef("*n or a0,a1,a0") 
                     ENDCASE

      CASE f_xor:    cvf("XOR") // a := b NEQV a
                     writef("*n xor a0,a1,a0") 
                     ENDCASE

      CASE f_eqv:    cvf("EQV") // a := b EQV a 
                     writef("*n xor a0,a1,a0")
                     writef("*n xori a0,a0,-1")
                     ENDCASE

      CASE f_gbyt:   cvf("GBYT") // a := b % a
                     writef("*n slli t0,a1,3")
                     writef("*n add t0,t0,a0")
                     writef("*n lbu a0,0(t0)")
                     ENDCASE

      CASE f_xgbyt:  cvf("XGBYT") // a := a % b 
                     writef("*n slli t0,a0,3")
                     writef("*n add t0,t0,a1")
                     writef("*n lbu a0,0(t0)")
                     ENDCASE

      CASE f_pbyt:   cvf("PBYT") // b % a := c
                     writef("*n slli t0,a1,3")
                     writef("*n add t0,t0,a0")
                     writef("*n sb a2,0(t0)")
                     ENDCASE

      CASE f_xpbyt:  cvf("XPBYT") // a % b := c 
                     writef("*n slli t0,a0,3")
                     writef("*n add t0,t0,a1")
                     writef("*n sb a2,0(t0)")
                     ENDCASE

// swb       Kn Ld K1 L1 ... Kn Ln   Binary chop switch, Ld default
      CASE f_swb:    cvswb()
                     ENDCASE

// swl       Kn Ld L1 ... Ln         Label vector switch, Ld default
      CASE f_swl:    cvswl()
                     ENDCASE

      CASE f_xch:    cvf("XCH") // swap a and b
                     writef("*n addi t0,a0,0")
                     writef("*n addi a0,a1,0")
                     writef("*n addi a1,t0,0")
                     ENDCASE

      CASE f_atb:    cvf("ATB") // b := a
                     writef("*n addi a1,a0,0")
                     ENDCASE

      CASE f_atc:    cvf("ATC") // c := a
                     writef("*n addi a2,a0,0")
                     ENDCASE

      CASE f_bta:    cvf("BTA") // a := b
                     writef("*n addi a0,a1,0")
                     ENDCASE

      CASE f_btc:    cvf("BTC") // c := b
                     writef("*n addi a2,a1,0")
                     ENDCASE

      CASE f_atblp:  cvfp("ATBLP") // b := a; a := P!n
                     atb()
                     base.n.add.fetch.a.set(3, pval)
                     ENDCASE

      CASE f_atblg:  cvfg("ATBLG") // b := a; a := G!n
                     atb()
                     base.n.add.fetch.a.set(4, gval)
                     ENDCASE

      CASE f_atbl:   cvfk("ATBL") // b := a; a := k
                     atb()
                     lit.a.set(kval)
                     ENDCASE

      CASE f_j:      cvfl("J") // jump to Ln
                     writef("*n jal x0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_rtn:    cvf("RTN") // procedure return
                     writef("*n ld ra,8(a3)")
                     writef("*n ld a3,0(a3)")
                     writef("*n jalr x0,0(ra)")
                     ENDCASE

      CASE f_goto:   cvf("GOTO") // jump to a
                     writef("*n jalr x0,0(a0)")
                     ENDCASE

      CASE f_res:    cvf("RES")   // <res> := A
                                  // <res> is already in A
                                  // nothing to do
                     ENDCASE

      CASE f_ldres:  cvf("LSRES") // A := <res>
                                  // A and B already set properly
                     ENDCASE

      CASE f_ikp:    cvfkp("IKP") // a := P!n + k; P!n := a
                     base.n.add.fetch.lit.add.a.set(3, pval, kval)
                     base.n.add.a.store(3, pval)
                     ENDCASE

      CASE f_ikg:    cvfkg("IKG") // a := G!n + k; G!n := a
                     base.n.add.fetch.lit.add.a.set(4, gval, kval)
                     base.n.add.a.store(4, gval)
                     ENDCASE

      CASE f_ikl:    cvfkl("IKL") // a := !Ln + k; !Ln := a
                     label.fetch.a.set(modletter, lval)
                     lit.add(kval)
                     label.a.store('L', modletter, lval)
                     ENDCASE

      CASE f_ip:     cvfp("IP") // a := P!n + a; P!n := a
                     base.n.add.fetch.a.add(3, pval)
                     base.n.add.a.store(3, pval)
                     ENDCASE

      CASE f_ig:     cvfg("IG") // a := G!n + a; G!n := a
                     base.n.add.fetch.a.add(4, gval)
                     base.n.add.a.store(4, gval)
                     ENDCASE

      CASE f_il:     cvfl("IL") // a := !Ln + a; !Ln := a
                     label.fetch.reg.set(modletter, lval, "t0")
                     writef("*n add a0,a0,t0")
                     label.a.store(modletter, lval)
                     ENDCASE

      CASE f_jeq:    cvfl("JEQ") // Jump to Ln if b = a
                     writef("*n beq a1,a0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jne:    cvfl("JNE") // Jump to Ln if b ~= a
                     writef("*n bne a1,a0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jls:    cvfl("JLS") // Jump to Ln if b < a
                     writef("*n blt a1,a0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jgr:    cvfl("JGR") // Jump to Ln if b > a
                     writef("*n blt a0,a1,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jle:    cvfl("JLE") // Jump to Ln if b <= a
                     writef("*n bge a0,a1,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jge:    cvfl("JGE") // Jump to Ln if b >= a
                     writef("*n bge a1,a0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jeq0:   cvfl("JEQ0") // Jump to Ln if a = 0
                     writef("*n beq a0,x0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jne0:   cvfl("JNE0") // Jump to Ln if a ~= 0
                     writef("*n bne a0,x0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jls0:   cvfl("JLS0") // Jump to Ln if a < 0
                     writef("*n blt a0,x0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jgr0:   cvfl("JGR0") // Jump to Ln if a > 0
                     writef("*n blt x0,a0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jle0:   cvfl("JLE0") // Jump to Ln if a <= 0
                     writef("*n bge x0,a0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jge0:   cvfl("JGE0") // Jump to Ln if a >= 0
                     writef("*n bge a0,x0,L%c%n", modletter, lval)
                     ENDCASE

      CASE f_jge0m:  cvfm("JGE0M") // Jump to Mn if a >= 0
                     writef("*n bge a0,x0,M%c%n", modletter, mval)
                     ENDCASE

      // The following five opcodes are never generated by
      // the BCPL compiler
      CASE f_brk:    cvf("BRK") // Breakpoint instruction
                     writef("*n ebreak")
                     ENDCASE

      CASE f_nop:    cvf("NOP") // No operation
                     ENDCASE

      CASE f_chgco:  cvf("CHGCO") // Change coroutine
                     writef("*n |unimplemented")
                     ENDCASE

      CASE f_mdiv:   cvf("MDIV") // a := Muldiv(P!3, P!4, P!5) 
                     writef("*n |unimplemented")
                     ENDCASE

      CASE f_sys:    cvf("SYS") // System function
                     writef("*n |unimplemented")
                     ENDCASE

      CASE f_section:  cvfs("SECTION") // Name of section
                       FOR i = 0 TO charv%0 DO sectname%i := charv%i
                       ENDCASE

      CASE f_modstart: cvf("MODSTART") // Start of module  
                       sectname%0 := 0
                       ENDCASE

      CASE f_modend:   cvf("MODEND") // End of module 
                       modletter := modletter+1
                       ENDCASE

      CASE f_global:   cvglobal() // Global initialisation data
                       ENDCASE

      CASE f_string:   cvstring() // String constant
                       ENDCASE

      CASE f_const:    cvconst() // Large integer constant
                       ENDCASE

      CASE f_static:   cvstatic() // Static variable or table
                       ENDCASE

      CASE f_mlab:     cvfm("MLAB") // Destination of jge0m
                       writef("*nM%c%n:", modletter, mval)
                       ENDCASE

      CASE f_lab:      cvfl("LAB") // Program label
                       writef("*nL%c%n:", modletter, lval)
                       ENDCASE

      CASE f_lstr:     cvfm("LSTR") // a := Mn   (pointer to string)
                       label.addr.reg.set("a0", 'M', modletter, mval)
                       writef("*n srai a0,a0,3")
                       ENDCASE

      CASE f_entry:    cventry() // Start of a function
                       ENDCASE
   $)

   newline()
$) REPEAT

AND cvf(s)  BE writef(";  %s", s)
AND cvfp(s) BE writef(";  %t7 P%n", s, rdp())
AND cvfkp(s) BE writef(";  %t7 K%n P%n", s, rdk(), rdp())
AND cvfg(s) BE writef(";  %t7 G%n", s, rdg())
AND cvfkg(s) BE writef(";  %t7 K%n G%n", s, rdk(), rdg())
AND cvfkl(s) BE writef(";  %t7 K%n L%n", s, rdk(), rdl())
AND cvfpg(s) BE writef(";  %t7 P%n G%n", s, rdp(), rdg())
AND cvfk(s) BE writef(";  %t7 K%n", s, rdk())
AND cvfw(s) BE writef(";  %t7 W%n", s, rdw())
AND cvfl(s) BE writef(";  %t7 L%n", s, rdl())
AND cvfm(s) BE writef(";  %t7 M%n", s, rdm())

AND cvswl() BE
$( LET n = rdk()
   LET l = rdl()
   LET lab = nextlab()
   writef(";  SWL K%n L%n", n, l)

   // if A < 0 then default
   writef("*n blt a0,x0,L%c%n", modletter, l)

   // if A >= n then default (DEBUG: ISSUE: TODO: A > n instead??)
   lit.reg.set(n, "t0")
   writef("*n bge a0,t0,L%c%n", modletter, l)

   // T0 -> switch table
   label.addr.reg.set("t0", 'S', modletter, lab)

   // dispatch to the A-th element of T0
   writef("*n slli a0,a0,3")
   writef("*n add t0,a0,t0")
   writef("*n ld t0,0(t0)")
   writef("*n jalr x0,0(t0)")

   // Emit case label table
   writef("*n align 8")
   writef("*nS%c%n:", modletter, lab)
   FOR i = 1 TO n DO
   {
      writef("*n;  L%n", rdl())
      writef("*n dword L%c%n", modletter, lval)
   }
$)

AND cvswb() BE
$( LET n = rdk()
   LET l = rdl() // default
   writef(";  SWB K%n L%n", n, l)
   // unoptimized - implements a linear search through the leaves of a binary tree
   // see documentation in BCPL manual for sial-686 code to see a proper tree walk
   // implementation.
   FOR i = 1 TO n DO 
   $( LET k = rdk()
      LET l = rdl() // case
      writef("*n ;  CASE K%n L%n", k, l)
      lit.reg.set(k, "t0")
      writef("*n beq a0,t0,L%c%n", modletter, l)
   $)
   writef("*n jal x0,L%c%n", modletter, l)
$)

AND cvglobal() BE
$( LET n = rdk()
   writef(";  GLOBAL K%n*n", n)
   IF sectname%0=0 FOR i = 0 TO 4 DO sectname%i := "prog"%i
   writef("*n; xdef %s*n", sectname)
   writef("%s:*n", sectname)
   FOR i = 1 TO n DO
   $( LET g = rdg()
      LET n = rdl()
      writef(";  G%n L%n*n", g, n)
      label.addr.reg.set("t0", 'L', modletter, n)
      writef("*n sd t0,%n(a0)*n", 8*g)
   $)
   writef(";  G%n", rdg()) // total size of the global vector, I think
   writef("*n jalr x0,0(ra)")
$)

AND rdchars() = VALOF
{ LET n = rdk()
  charv%0 := n
  FOR i = 1 TO n DO charv%i := rdc()
  RESULTIS n
}

AND cvstring() BE
$( LET lab = rdm()
   LET n = rdchars()
   writef(";  STRING  M%n K%n", lab, n)
   FOR i = 1 TO n DO writef(" C%n", charv%i)
   // writef("*n .data")
   writef("*n align 8")
   writef("*nM%c%n:", modletter, lab)
   FOR i = 0 TO n DO writef("*n byte %n", charv%i)
   writef("*n align 8")
   // writef("*n .text")
$)

AND cvconst() BE
$( LET lab = rdm()
   LET w = rdw()
   writef(";  CONST   M%n W%n", lab, w)
   // writef("*n .data")
   writef("*n align 8")
   writef("*nM%c%n:", modletter, lab)
   writef("*n dword %n", w)
   //writef("*n .text")
$)

AND cvstatic() BE
$( LET lab = rdl()
   LET n = rdk()
   writef(";  STATIC  L%n K%n", lab, n)
   // writef("*n .data")
   writef("*n align 8")
   writef("*nL%c%n:", modletter, lab)
   FOR i = 1 TO n DO { writef("*n ;  W%n", rdw())
                       writef("*n dword %n", wval)
                     }
   // writef("*n .text")
$)

AND cvfs(s) BE
$( LET n = rdchars()
   writef(";  %t7 K%n", s, n)
   FOR i = 1 TO n DO writef(" C%n", charv%i)
$)

AND cventry() BE
$( LET n = rdchars()
   LET op = rdf()
   LET lab = rdl()
   writef("*n;  Entry to: %s*n", charv)
   writef(";  %t7 K%n", "ENTRY", n)
   FOR i = 1 TO n DO writef(" C%n", charv%i)
   newline()
   TEST op=f_lab THEN writef(";  LAB     L%n*n", lab)
                 ELSE writef(";  Bad op F%n L%n*n", op, lab)
   writef("*nL%c%n:", modletter, lab)
   writef("*n sd ra,8(a3)")   // P!1 := m/c return address
   writef("*n sd t0,16(a3)")  // P!2 := entry address
   writef("*n sd a0,24(a3)")  // P!3 := arg1
$)
